jadwalkegiatan/urls.py
from django.urls import path
from .import views

app_name = 'jadwalkegiatan'

urlpatterns = [
 	path('add', views.addForm, name='addForm'),
 	path('',  views.jadwal, name='jadwal'),
 	path('delete', views.delete)
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from jadwalkegiatan.views import addForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jadwalkegiatan.urls')),
]

jadwalkegiatan/models.py
from django.db import models
import datetime
from django.utils import timezone

class Jadwal(models.Model):
    nama_kegiatan = models.CharField(max_length=50)
    tempat = models.CharField(max_length=25)
    prioritas = models.CharField(null=True, max_length=25)
    tanggal = models.DateField(default=timezone.now)
    waktu = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.nama_kegiatan

# Create your models here.

jadwalkegiatan/forms.py
from . import models
from django import forms

class JadwalForm(forms.ModelForm):
        nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Nama Kegiatan",
                }))
        tempat = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Tempat",
                }))
        prioritas = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Prioritas",
                }))
        tanggal = forms.DateField(widget=forms.SelectDateWidget(attrs={
                "class" : "datefield jadwalfields",
                "required" : True,
                }))
        waktu = forms.TimeField(widget=forms.TimeInput(attrs={
                "class" : "datefield jadwalfields",
                "placeholder":"00:00",
                "required" : True,
                }))


        class Meta:
                model = models.Jadwal
                fields = ["nama_kegiatan", "prioritas", "tempat", "tanggal","waktu"]        

jadwalkegiatan/views.py
from django.shortcuts import render, redirect	
from django.http import HttpResponse
from .forms import JadwalForm
from .models import Jadwal
from django.utils import timezone
import datetime

def addForm(request):
    form = JadwalForm()
    if request.method =="POST":
        form=JadwalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('jadwalkegiatan:jadwal')
    return render(request, "addform.html", {'form':form})

def jadwal(request):
    # print(dir(request.body))
    jadwals = Jadwal.objects.order_by("tanggal", "waktu")

    response = {
        'jadwal' :jadwals,
        'server_time' : timezone.now(),
    }
    return render(request, "formpage.html", response)
# Create your views here.

def delete(request):
    if request.method == "POST":
        id = request.POST['id']
        Jadwal.objects.get(id=id).delete()
    return redirect('jadwalkegiatan:jadwal')

jadwalkegiatan/templates/addform.html
<!DOCTYPE HTML>
{% load static %}
<head>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.css' %}" />
	<link href="https://fonts.googleapis.com/css?family=Proxima+Nova" rel="stylesheet">

<style>
html{
	background-color:#D5DFD9;
	padding:20px;

}
h2{
	margin:20px;
	font-family:Proxima Nova;
}
.navbar{
	background-color:#3C455C;
}
#field{
	margin:20px;
	padding-bottom:30px;
}
#text-jadwal, #text-create{
	font-family:Proxima Nova;
	font-size:18px;
	color:white;
}
</style>
</head>

<html>

 <nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="{% url 'jadwalkegiatan:jadwal' %}" id="text-jadwal"> <b> My Jadwal</b> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'jadwalkegiatan:addForm' %}" id="text-create"><b> Create Jadwal </b> <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <span class="navbar-text">
    </span>
  </div>
</nav>


<!-- Columns start at 50% wide on mobile and bump up to 33.3% wide on desktop -->
<!-- Columns are always 50% wide, on mobile and desktop -->
<div class="row">
  <div class="col-6"></div>
  <div class="col-6"></div>
</div>




<h2> Tambahkan Jadwal </h2>

<div class="col-8" id="field">
<form method="POST" class="form">
	{% csrf_token %}
	<p>Nama Kegiatan</p>
    {{ form.nama_kegiatan }}
    <p><br/>Tempat</p>
    {{ form.tempat }}
    <p><br/>Prioritas</p>
    {{ form.prioritas }}
    <p><br/></p>
    {{ form.tanggal }}
    <p><br/></p>
    {{ form.waktu }}
    <p><br/></p>
       <div class="full">
                <input type="submit" class="button" value="Submit" />
            </div>
</form>

</html>

jadwalkegiatan/templates/formpage.html
<!DOCTYPE HTML>
{% load static %}
<html>

<head>
<link href="https://fonts.googleapis.com/css?family=Proxima+Nova" rel="stylesheet">
<style>
html{
	background-color:#D5DFD9;
	padding:20px;
}
.row{
	margin:20px;
}

#listjadwal{
	margin-left:30px;
}
h2{
	margin:20px;
	font-family:Proxima Nova;
}
#text-create, #text-jadwal{
	color:white;
	font-family:Proxima Nova;
	font-size:18px;
}
p{
	font-size:15px;
	font-family:Arial;
}
.navbar{
	background-color:#3C455C;
}

</style>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.css' %}" />
</head>


<body>

 <nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="{% url 'jadwalkegiatan:jadwal' %}" id="text-jadwal"> <b>My Jadwal </b> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'jadwalkegiatan:addForm' %}" id="text-create" > <b>Create Jadwal</b> <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <span class="navbar-text">
    </span>
  </div>
</nav>


<div class="row">
  <div class="col-6"><h2> Daftar Jadwal </h2></div>
  <div class="col-6"></div>
</div>

<div class="col-8" id="listjadwal">
{% for j in jadwal %}
            <div class="jadwal-card">
                <h4>{{ j.nama_kegiatan }}</h4>
                <div class="flex">
                    <div>
                        <p> Di {{ j.tempat }}<br/>
                        Prioritas: {{ j.prioritas }} </p>
                    </div>
                    <div>
                        <p> Date: {{ j.tanggal }}<br/>
                        Time: {{ j.waktu }} </p>
                    </div>

                    <form action="delete" method="POST" >
                        {% csrf_token %}
                        <input type="hidden" value="{{ j.id }}" name="id" />
                        <input class="button delete" type="submit" value="Delete" />
                        <p><br/> </p>
                    </form>
                </div>
            </div>
        {% endfor %}
</div>


</body>
</html>